# Exported from Render on 2026-08-06T15:46:43Z
version: "1"
services:
- type: web
  name: kopabridge
  runtime: docker
  repo: https://github.com/paowuor/kopabridge
  plan: free
  region: oregon
  dockerContext: .apps/api/Dockerfile
  dockerfilePath: docker compose up --build
  autoDeployTrigger: commit
